version: 2

sources:
  - name: QWT_RAW
    database:"{{env_var('DBT_SOURCEDB', 'QWT_ANALYTICS')}}"
    schema:"{{env_var('DBT_SOURCESCHEMA', 'RAW')}}"
    tables:
      - name: customer
      - name: products
      - name: orders
      - name: orderdetails
      - name: categories
      - name: suppliers
      - name: shipments
